#############################################################################
# Makefile for building: fontweightissue.app/Contents/MacOS/fontweightissue
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  fontweightissue.pro
# Template: app
# Command: /opt/local/bin/qmake-qt5 -o Makefile fontweightissue.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I. -I/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers -I/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers -I/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers/5.4.1 -I/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers/5.4.1/QtGui -I/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers -I/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/5.4.1 -I/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/5.4.1/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Volumes/Debian/MP9/share/qt5/mkspecs/macx-clang -F/opt/local/libexec/qt5/Library/Frameworks
QMAKE         = /opt/local/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = fontweightissue1.0.0
DISTDIR = /Volumes/Debian/Users/bertin/work/src/new/Qt/fontweightissue-qt5/.tmp/fontweightissue1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -mmacosx-version-min=10.7 -Wl,-rpath,/opt/local/libexec/qt5/Library/Frameworks
LIBS          = $(SUBLIBS) -F/opt/local/libexec/qt5/Library/Frameworks -framework QtWidgets -framework QtGui -framework QtCore -framework AppKit -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = dialog.cpp \
		main.cpp moc_dialog.cpp
OBJECTS       = dialog.o \
		main.o \
		moc_dialog.o
DIST          = /Volumes/Debian/MP9/share/qt5/mkspecs/features/spec_pre.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/qdevice.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/device_config.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/shell-unix.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/unix.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/mac.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/macx.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/gcc-base.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/gcc-base-mac.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/clang.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/clang-mac.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/qconfig.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_designer.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_help.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_macextras.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_macextras_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/qt_functions.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/qt_config.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/macx-clang/qmake.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/exclusive_builds.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/default_pre.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/default_pre.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/resolve_config.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/default_post.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/sdk.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/default_post.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/objective_c.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/warn_on.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/qt.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/resources.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/moc.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/unix/opengl.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/uic.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/unix/thread.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/rez.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/testcase_targets.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/exceptions.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/yacc.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/lex.prf \
		fontweightissue.pro dialog.h dialog.cpp \
		main.cpp
QMAKE_TARGET  = fontweightissue
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = fontweightissue.app/Contents/MacOS/fontweightissue

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d fontweightissue.app/Contents/MacOS/ || mkdir -p fontweightissue.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fontweightissue.pro /Volumes/Debian/MP9/share/qt5/mkspecs/macx-clang/qmake.conf /Volumes/Debian/MP9/share/qt5/mkspecs/features/spec_pre.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/qdevice.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/device_config.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/shell-unix.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/unix.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/mac.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/macx.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/gcc-base.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/gcc-base-mac.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/clang.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/common/clang-mac.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/qconfig.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_core.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_designer.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_gui.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_help.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_location.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_location_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_macextras.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_macextras_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_network.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qml.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quick.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_script.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sql.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_svg.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webchannel.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webengine.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webengine_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginecore.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xml.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_phonon4qt5.pri \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/qt_functions.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/qt_config.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/macx-clang/qmake.conf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/exclusive_builds.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/default_pre.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/default_pre.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/resolve_config.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/default_post.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/sdk.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/default_post.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/objective_c.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/warn_on.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/qt.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/resources.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/moc.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/unix/opengl.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/uic.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/unix/thread.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/rez.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/testcase_targets.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/exceptions.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/yacc.prf \
		/Volumes/Debian/MP9/share/qt5/mkspecs/features/lex.prf \
		fontweightissue.pro \
		/opt/local/libexec/qt5/Library/Frameworks/QtWidgets.framework/QtWidgets.prl \
		/opt/local/libexec/qt5/Library/Frameworks/QtGui.framework/QtGui.prl \
		/opt/local/libexec/qt5/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile fontweightissue.pro
/Volumes/Debian/MP9/share/qt5/mkspecs/features/spec_pre.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/qdevice.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/device_config.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/common/shell-unix.conf:
/Volumes/Debian/MP9/share/qt5/mkspecs/common/unix.conf:
/Volumes/Debian/MP9/share/qt5/mkspecs/common/mac.conf:
/Volumes/Debian/MP9/share/qt5/mkspecs/common/macx.conf:
/Volumes/Debian/MP9/share/qt5/mkspecs/common/gcc-base.conf:
/Volumes/Debian/MP9/share/qt5/mkspecs/common/gcc-base-mac.conf:
/Volumes/Debian/MP9/share/qt5/mkspecs/common/clang.conf:
/Volumes/Debian/MP9/share/qt5/mkspecs/common/clang-mac.conf:
/Volumes/Debian/MP9/share/qt5/mkspecs/qconfig.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_core.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_core_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_dbus.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_declarative.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_designer.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_enginio.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_gui.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_help.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_help_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_location.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_location_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_macextras.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_macextras_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_network.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_network_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_nfc.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_opengl.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_positioning.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qml.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quick.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_script.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_script_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sensors.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_serialport.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sql.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_svg.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_testlib.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_uitools.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webchannel.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webchannel_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webengine.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webengine_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginecore.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkit.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_websockets.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_widgets.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xml.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/modules/qt_phonon4qt5.pri:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/qt_functions.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/qt_config.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/macx-clang/qmake.conf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/exclusive_builds.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/default_pre.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/default_pre.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/resolve_config.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/default_post.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/sdk.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/default_post.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/objective_c.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/warn_on.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/qt.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/resources.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/moc.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/unix/opengl.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/uic.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/unix/thread.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/mac/rez.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/testcase_targets.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/exceptions.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/yacc.prf:
/Volumes/Debian/MP9/share/qt5/mkspecs/features/lex.prf:
fontweightissue.pro:
/opt/local/libexec/qt5/Library/Frameworks/QtWidgets.framework/QtWidgets.prl:
/opt/local/libexec/qt5/Library/Frameworks/QtGui.framework/QtGui.prl:
/opt/local/libexec/qt5/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile fontweightissue.pro

qmake_all: FORCE

fontweightissue.app/Contents/PkgInfo: 
	@test -d fontweightissue.app/Contents || mkdir -p fontweightissue.app/Contents
	@$(DEL_FILE) fontweightissue.app/Contents/PkgInfo
	@echo "APPL????" >fontweightissue.app/Contents/PkgInfo
fontweightissue.app/Contents/Resources/empty.lproj: 
	@test -d fontweightissue.app/Contents/Resources || mkdir -p fontweightissue.app/Contents/Resources
	@touch fontweightissue.app/Contents/Resources/empty.lproj
	
fontweightissue.app/Contents/Info.plist: 
	@test -d fontweightissue.app/Contents || mkdir -p fontweightissue.app/Contents
	@$(DEL_FILE) fontweightissue.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.fontweightissue,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,fontweightissue,g" -e "s,@TYPEINFO@,????,g" /Volumes/Debian/MP9/share/qt5/mkspecs/macx-clang/Info.plist.app >fontweightissue.app/Contents/Info.plist

all: Makefile \
		fontweightissue.app/Contents/PkgInfo \
		fontweightissue.app/Contents/Resources/empty.lproj \
		fontweightissue.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents dialog.h $(DISTDIR)/
	$(COPY_FILE) --parents dialog.cpp main.cpp $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r fontweightissue.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp
moc_dialog.cpp: /Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		dialog.h
	/opt/local/libexec/qt5/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -I/opt/local/share/qt5/mkspecs/macx-clang -I/Volumes/Debian/Users/bertin/work/src/new/Qt/fontweightissue-qt5 -I/opt/local/libexec/qt5/Library/Frameworks/QtWidgets.framework/Headers -I/opt/local/libexec/qt5/Library/Frameworks/QtGui.framework/Headers -I/opt/local/libexec/qt5/Library/Frameworks/QtGui.framework/Headers/5.4.1 -I/opt/local/libexec/qt5/Library/Frameworks/QtGui.framework/Headers/5.4.1/QtGui -I/opt/local/libexec/qt5/Library/Frameworks/QtCore.framework/Headers -I/opt/local/libexec/qt5/Library/Frameworks/QtCore.framework/Headers/5.4.1 -I/opt/local/libexec/qt5/Library/Frameworks/QtCore.framework/Headers/5.4.1/QtCore -I/opt/local/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1/backward -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/6.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include -F/opt/local/libexec/qt5/Library/Frameworks dialog.h -o moc_dialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

dialog.o: dialog.cpp /Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/QtGlobal \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/qglobal.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QtWidgets \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/complexwidgets.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/itemviews.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qaccessiblemenu.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qaccessiblewidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qaccessiblewidgets.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/rangecontrols.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/simplewidgets.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcolordialog.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qdialog.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qerrormessage.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qfiledialog.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qfilesystemmodel.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qfontdialog.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qinputdialog.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qmessagebox.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qprogressdialog.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwizard.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicseffect.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsanchorlayout.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsgridlayout.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsitem.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsitemanimation.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicslayout.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicslayoutitem.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicslinearlayout.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsproxywidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsscene.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicssceneevent.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicstransform.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicsview.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgraphicswidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractitemdelegate.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractitemview.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcolumnview.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qdatawidgetmapper.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qdirmodel.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qfileiconprovider.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qheaderview.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qitemdelegate.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qitemeditorfactory.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlistview.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlistwidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qstyleditemdelegate.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtableview.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtablewidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtreeview.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtreewidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtreewidgetitemiterator.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qaction.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qactiongroup.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qboxlayout.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qdesktopwidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qformlayout.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgesture.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgesturerecognizer.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgridlayout.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlayout.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlayoutitem.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qopenglwidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qshortcut.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qsizepolicy.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qstackedlayout.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtooltip.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwhatsthis.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidgetaction.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qkeyeventtransition.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qmouseeventtransition.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcommonstyle.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qdrawutil.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qproxystyle.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qstyle.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qstylefactory.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qstyleoption.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qstylepainter.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qstyleplugin.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcolormap.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcompleter.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qscroller.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qscrollerproperties.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qsystemtrayicon.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qundogroup.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qundostack.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qundoview.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractbutton.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractscrollarea.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractslider.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qabstractspinbox.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qbuttongroup.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcalendarwidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcheckbox.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcombobox.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qcommandlinkbutton.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qdatetimeedit.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qdial.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qdialogbuttonbox.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qdockwidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qfocusframe.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qfontcombobox.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qframe.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qgroupbox.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qkeysequenceedit.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlabel.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlcdnumber.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qlineedit.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qmdiarea.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qmdisubwindow.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qmenu.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qmenubar.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qplaintextedit.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qprogressbar.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qpushbutton.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qradiobutton.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qrubberband.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qscrollarea.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qscrollbar.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qsizegrip.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qslider.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qspinbox.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qsplashscreen.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qsplitter.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qstackedwidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qstatusbar.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtabbar.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtabwidget.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtextbrowser.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtextedit.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtoolbar.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtoolbox.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtoolbutton.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qtwidgetsversion.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers/5.4.1/QtGui/private/qfontengine_p.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers/5.4.1/QtGui/private/qtextengine_p.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers/5.4.1/QtGui/private/qtextformat_p.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers/5.4.1/QtGui/private/qfont_p.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers/5.4.1/QtGui/private/qfixed_p.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers/5.4.1/QtGui/private/qtextdocument_p.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/5.4.1/QtCore/private/qobject_p.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers/5.4.1/QtGui/private/qfragmentmap_p.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/5.4.1/QtCore/private/qtools_p.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtGui.framework/Versions/5/Headers/5.4.1/QtGui/private/qcssparser_p.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/5.4.1/QtCore/private/qunicodetools_p.h \
		dialog.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

main.o: main.cpp /Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QApplication \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qapplication.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/QTranslator \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/qtranslator.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/QLocale \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/qlocale.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/QLibraryInfo \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtCore.framework/Versions/5/Headers/qlibraryinfo.h \
		dialog.h \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/QWidget \
		/Volumes/Debian/MP9/libexec/qt5/Library/Frameworks/QtWidgets.framework/Versions/5/Headers/qwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/Applications/MacPorts/Qt5/examples/widgets/dialogs/fontweightissue || mkdir -p $(INSTALL_ROOT)/Applications/MacPorts/Qt5/examples/widgets/dialogs/fontweightissue
	$(DEL_FILE) -r "$(INSTALL_ROOT)/Applications/MacPorts/Qt5/examples/widgets/dialogs/fontweightissue/fontweightissue.app"
	
	-$(INSTALL_DIR) "fontweightissue.app" "$(INSTALL_ROOT)/Applications/MacPorts/Qt5/examples/widgets/dialogs/fontweightissue/fontweightissue.app"

uninstall_target: FORCE
	-$(DEL_FILE) -r "$(INSTALL_ROOT)/Applications/MacPorts/Qt5/examples/widgets/dialogs/fontweightissue/fontweightissue.app"
	-$(DEL_DIR) $(INSTALL_ROOT)/Applications/MacPorts/Qt5/examples/widgets/dialogs/fontweightissue/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

